DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);


CREATE TABLE IF NOT EXISTS shopping_list (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    price decimal(10,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false,
    category grocery NOT NULL
);
-- enum = list of options that may be used by columns in table rows


-- CREATE TABLE IF NOT EXISTS amazong_products (
--     product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name TEXT NOT NULL,
--     price decimal(12,2) NOT NULL,
--     image TEXT,
--     category department NOT NULL
-- );

